### ISSUE TITLE
SQLite3 module is missing

### ISSUE THREAD

**Issue by nduijvelshoff** [chadly/ghost#2]
After deployment I get the following error in my log stream:
```
$ npm install sqlite3 --save
Error: Cannot find module 'D:\home\site\wwwroot\node_modules\sqlite3\lib\binding\node-v57-win32-ia32\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (D:\home\site\wwwroot\node_modules\knex\lib\dialects\sqlite3\index.js:75:12)
    at Client_SQLite3.initializeDriver (D:\home\site\wwwroot\node_modules\knex\lib\client.js:219:26)
    at Client_SQLite3.Client (D:\home\site\wwwroot\node_modules\knex\lib\client.js:113:10)
    at new Client_SQLite3 (D:\home\site\wwwroot\node_modules\knex\lib\dialects\sqlite3\index.js:58:20)
```

This results in a 500 error for my browser.

**Comment by chadly** [comment]
How did you deploy? The azure machine needs to install the `node_modules` (e.g. you shouldn't FTP the `node_modules` folder up there).

If you did let kudu deploy it, I would just try deleting the `node_modules` folder in azure and let it reinstall it.

**Comment by nduijvelshoff** [comment]
Hi Chadly,

Can it be because of the fact that "sqlite3" is not a dependency?

**package.json**
```
  "optionalDependencies": {
    "sqlite3": "3.1.8"
  },
```

**Comment by mchikhaoui** [comment]
@nduijvelshoff 

you have to upgrade your nodeJs version to 8.9.0 then delete node_modules folder and run npm install

**Comment by chadly** [comment]
Thanks, @mchikhaoui
